### PR TITLE
Add html, css and JS files for review

### PR DESCRIPTION
**Pull request by Ney2**
This is a PR request for a to-do-list review. 
1. Add HTML, CSS, and JS file
2. Use modules
3. Configure web pack

### CODE REVIEW

**Review by eudondian — CHANGES_REQUESTED** [review]
Good Job!
-Followed javaScript rules
-Followed DRY, KISS and Y
-Followed HTML and CSS rules

Change required
Your link to the live demo doesn't have the expected link. kindly use the link below as a guide to set up your live demo'
https://github.com/turingschool-examples/webpack-starter-kit/blob/main/gh-pages-procedure.md 

image

**Comment by Ney2** [comment]
Update Readme.md file with the correct link to the deployed page.

**Review by eudondian — CHANGES_REQUESTED** [review]
Great work on the attempt to make the changes requested in the previous review.
Your live Demo is not still working. Kindly follow the steps diligently on the link and sent earlier to achieve this.
image

**Review by eudondian — APPROVED** [review]
You did a great job! 
Congratulations!

**Comment by Ney2** [comment]
Thank you for your feedback. 😃

**Pull request merged**
